### ISSUE TITLE
Symbol void: prefix-command-preserve-state

### ISSUE THREAD

**Issue by bymoz089** [hrehfeld/emacs-smart-hungry-delete#1]
after installing from melpa and putting following lines in my init.el:
```
(require 'smart-hungry-delete)
(smart-hungry-delete-add-default-hooks)
(global-set-key (kbd "<backspace>") 'smart-hungry-delete-backward-char)
(global-set-key (kbd "C-d") 'smart-hungry-delete-forward-char)

```

I get just the following error messages at pressing `backspace` or `C-d`:

smart-hungry-delete-backward-char: Symbol's function definition is void: prefix-command-preserve-state

I'm using: GNU Emacs 24.5.1 on Linux

**Comment by seagle0128** [comment]
Same issue here, with GNU Emacs 24.5 on Ubuntu 16.04. I am using ivy/swiper.

```elisp
smart-hungry-delete-backward-char: Symbol's function definition is void: prefix-command-preserve-state [2 times]
```

**Comment by hrehfeld** [comment]
@seagle0128 @bymoz089 This is an Emacs 25 feature: https://git.gnu.io/gnu/emacs/commit/5dc644a6b01e2cf950ff617ab15be4bf1917c38c

The documentation says:

```
(defun prefix-command-preserve-state ()
  "Pass the current prefix command state to the next command.
Should be called by all prefix commands.
Runs `prefix-command-preserve-state-hook'."

```
Honestly I'm not sure If I should ignore "Should be called by all prefix commands." and don't really know how to work-around it missing in 24. For now I will just require emacs 25 instead of 24, but that will not help you.

Are you still on 24? Can you upgrade?

Sorry that this took so long to reply.

**Comment by hrehfeld** [comment]
:+1:
